title: BabelfishPG
description: ""
baseurl: "/babelfishpg-project-website/" # the subpath of your site, e.g. /blog
url: "https://ongres.github.io" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:path/
email: 
twitter_username:
github_username:

headings:
  news: "News"
  source: "Source Code"
  authors: "Authors"
  downloads: "Download & Get Started"

opensearch_version: 1.0.1
opensearch_major_minor_version: 1.0
lucene_version: 8_8_2

# Build settings
markdown: kramdown
remote_theme: pmarsceill/just-the-docs@v0.3.3

# Kramdown settings
kramdown:
  toc_levels: 2..3

logo: "/assets/images/logo.svg"

# Aux links for the upper right navigation
aux_links:

color_scheme: babelfishpg

defaults:
  - scope:
      type: "posts"
    values:
      permalink: blog/:categories/:year/:month/:title/
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
      permalink: /:collection/:name/
  - scope:
      type: javadocs
    values:
      layout: javadocs
      permalink: /:collection/:name.html
  - scope:
      type: events
    values:
      layout: event
      permalink: events/:title/
  - scope:
      type: versions
    values:
      layout: versions
      permalink: versions/:categories/:slug.html
  - scope:
      type: artifacts
    values:
      layout: artifact
      permalink: :collection/:categories/:slug.html

# Define Jekyll collections
collections:
  # Define a collection named "tests", its documents reside in the "_tests" directory
  architecture:
    permalink: /:collection/:path/
    output: true
  definition:
    permalink: /:collection/:path/
    output: true
  quickStart:
    permalink: /:collection/:path/
    output: true
  docs:
    output: true
  events:
    output: true
  artifacts:
    output: true
  versions:
    output: true
  docs:
    output: true
  faqs:
    output: true

paginate: 5
paginate_path: "/blog/page:num/"

just_the_docs:
  # Define the collections used in the theme
  collections:
    architecture:
      name: Babelfish Architecture
      # nav_exclude: true
      nav_fold: true
      # search_exclude: true
    definition:
      name: What is Babelfish
      # nav_exclude: true
      nav_fold: true
      # search_exclude: true
    quickStart:
      name: Quickstart Guide
      # nav_exclude: true
      nav_fold: true
      # search_exclude: true

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
ga_tracking: G-BQV14XK08F

# Disable the just-the-docs theme anchor links in favor of our custom ones
# See _includes/head_custom.html
heading_anchors: false

# Adds on-hover anchor links to h2-h6
anchor_links: true

footer_content:

# Build settings
plugins:
  - jekyll-remote-theme
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - bower.json
  - package.json
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md